"""create contacts table

Revision ID: 2b77e0f13601
Revises: 1805953507cf
Create Date: 2023-05-07 17:05:32.128343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b77e0f13601'
down_revision = '1805953507cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
