"""create contacts table

Revision ID: d207f813ac30
Revises: 2b77e0f13601
Create Date: 2023-05-07 20:05:13.651577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd207f813ac30'
down_revision = '2b77e0f13601'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
